### ISSUE TITLE
Errors generated when loading plugin

### ISSUE THREAD

**Issue by captconstruct** [Brandawg93/homebridge-fordpass#134]
**Describe the bug**
After updating and restarting the Homebridge, I received these errors.

[3/12/2021, 10:02:44 AM] [homebridge-fordpass] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Target State' was slow to respond! See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:44 AM] [homebridge-fordpass] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:44 AM] [homebridge-fordpass] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:44 AM] [homebridge-fordpass] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Target State' was slow to respond! See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:44 AM] [homebridge-fordpass] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:44 AM] [homebridge-fordpass] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:47 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 103.2612 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:48 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:51 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 103.2612 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:51 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:53 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 103.2612 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:53 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:56 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 103.2612 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:02:56 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:03:04 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/12/2021, 10:03:04 AM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 103.2612 exceeded maximum of 100. See https://git.io/JtMGR for more info.

**Debug Output**
No Debug output available

**To Reproduce**

1. Running on a RPI Zero, install latest version and restart system. The errors pop up occasionally.

**Expected behavior**
No errors appearing.

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Zero
On what iOS version are you having issues: N/A
Does this issue occur consistently or randomly: Regularly
If applicable, what was the last version that worked properly: Previous version from latest (1.3.0)
```

**Comment by Brandawg93** [comment]
Hi. I've published a new test copy that should fix these warnings. You can try it out by going to the plugins page, clicking the wrench next to homebridge-fordpass, clicking "install previous versions", and selecting v1.3.1-test.0.

Please let me know if this fixes these warnings for you so I can submit an official release.

**Comment by captconstruct** [comment]
That doesn’t look like it fixed the issue. Mine is still generating the battery level error. I verified I installed the test version then restarted. It’s acting the same.

Thanks for the help

From: Brandon McFarlin ***@***.***>
Reply-To: Brandawg93/homebridge-fordpass ***@***.***>
Date: Friday, March 12, 2021 at 11:46 AM
To: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Blake Singleton ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-fordpass] Errors generated when loading plugin (#134)


Hi. I've published a new test copy that should fix these warnings. You can try it out by going to the plugins page, clicking the wrench next to homebridge-fordpass, clicking "install previous versions", and selecting v1.3.1-test.0.

Please let me know if this fixes these warnings for you so I can submit an official release.

**Comment by Brandawg93** [comment]
Can you send me a copy of your logs with the new version installed? The warnings have disappeared on my instance after this test version.

**Comment by captconstruct** [comment]
Here you go:

[3/13/2021, 12:58:07 PM] [Homebridge UI] Running Command: sudo -E -n npm install -g ***@***.***
[3/13/2021, 12:58:32 PM] [Homebridge UI] Homebridge restart request received
[3/13/2021, 12:58:32 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[3/13/2021, 12:58:32 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[3/13/2021, 12:58:32 PM] Got SIGTERM, shutting down Homebridge...
[3/13/2021, 12:58:37 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[3/13/2021, 12:58:42 PM] [HB Supervisor] Restarting Homebridge...
[3/13/2021, 12:58:42 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[3/13/2021, 12:58:42 PM] [HB Supervisor] Started Homebridge v1.3.3 with PID: 5685
Initializing HAP-NodeJS v0.9.3...
[3/13/2021, 12:58:50 PM] Loaded config.json with 2 accessories and 3 platforms.
[3/13/2021, 12:58:50 PM] Loaded 2 cached accessories from cachedAccessories.
[3/13/2021, 12:58:50 PM] ---
[3/13/2021, 12:58:57 PM] Loaded plugin: ***@***.***
[3/13/2021, 12:58:57 PM] Registering platform 'homebridge-blinkcameras.BlinkCameras'
[3/13/2021, 12:58:57 PM] ---
[3/13/2021, 12:58:58 PM] Loaded plugin: ***@***.***
[3/13/2021, 12:58:58 PM] Registering platform 'homebridge-config-ui-x.config'
[3/13/2021, 12:58:58 PM] ---
[3/13/2021, 12:58:58 PM] Loaded plugin: ***@***.***
[3/13/2021, 12:58:58 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[3/13/2021, 12:58:58 PM] ---
[3/13/2021, 12:58:58 PM] Loaded plugin: ***@***.***
[3/13/2021, 12:58:58 PM] Registering platform 'homebridge-fordpass.FordPass'
[3/13/2021, 12:58:58 PM] ---
[3/13/2021, 12:58:58 PM] Loading 3 platforms...
[3/13/2021, 12:58:58 PM] [Config] Initializing config platform...
[3/13/2021, 12:58:58 PM] [Config] Running in Service Mode
[3/13/2021, 12:58:58 PM] [FordPass] Initializing FordPass platform...
[3/13/2021, 12:58:58 PM] [Blink Cameras] Initializing BlinkCameras platform...
[3/13/2021, 12:58:58 PM] [Blink Cameras] Init
[3/13/2021, 12:58:58 PM] Loading 2 accessories...
[3/13/2021, 12:58:58 PM] [Auto-Lock Switch] Initializing DummySwitch accessory...
[3/13/2021, 12:58:59 PM] [Auto-Lock Switch] Setting switch to true
[3/13/2021, 12:58:59 PM] [Garage Switch] Initializing DummySwitch accessory...
[3/13/2021, 12:58:59 PM] [Garage Switch] Setting switch to false
[3/13/2021, 12:58:59 PM] [FordPass] Configuring accessory F150
[3/13/2021, 12:58:59 PM] [FordPass] Configuring accessory Edge
[3/13/2021, 12:58:59 PM] [Blink Cameras] Finished Launching
[3/13/2021, 12:58:59 PM] [Blink Cameras] Discovering Cameras
[3/13/2021, 12:58:59 PM] [Blink Cameras] Authenticating with Blink API as ***@***.***
Making new blink client
Preparing Advertiser for 'Homebridge 1CD8 D209' using ciao backend!
Setup Payload:
X-HM://0024TJ9X3K8H0
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 816-34-807 │
    └────────────┘

Starting to advertise 'Homebridge 1CD8 D209' using ciao backend!
[3/13/2021, 12:59:00 PM] Homebridge v1.3.3 (Homebridge 1CD8) is running on port 51734.
[3/13/2021, 12:59:00 PM] [Blink Cameras] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: An app update is required
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[3/13/2021, 12:59:03 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:03 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:10 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:10 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:12 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:12 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:16 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:16 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:27 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 12:59:27 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:00:29 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:00:29 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:10:35 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:10:36 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:10:36 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:10:37 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:10:40 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:10:40 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:11:24 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:11:24 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:17:16 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:17:16 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:17:18 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:17:19 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:17:22 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:17:22 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:24:56 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:24:56 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:24:58 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:24:58 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:25:02 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:25:02 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:32:03 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:32:03 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:35:47 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:35:47 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:35:51 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:35:51 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:35:55 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:35:55 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 1:58:59 PM] [Blink Cameras] Discovering Cameras
[3/13/2021, 2:06:08 PM] [Auto-Lock Switch] Setting switch to false
[3/13/2021, 2:07:18 PM] [Garage Switch] Setting switch to true
[3/13/2021, 2:22:21 PM] [Garage Switch] Setting switch to false
[3/13/2021, 2:38:47 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:38:47 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:43:33 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:43:33 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:44:53 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:44:53 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:54:09 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:54:09 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 2:58:59 PM] [Blink Cameras] Discovering Cameras
[3/13/2021, 3:03:23 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 3:03:23 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 3:03:24 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 3:03:24 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 3:03:28 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 100.435104 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/13/2021, 3:03:28 PM] [homebridge-fordpass] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 101.413368 exceeded maximum of 100. See https://git.io/JtMGR for more info.

From: Brandon McFarlin ***@***.***>
Reply-To: Brandawg93/homebridge-fordpass ***@***.***>
Date: Saturday, March 13, 2021 at 1:43 PM
To: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Blake Singleton ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-fordpass] Errors generated when loading plugin (#134)


Can you send me a copy of your logs with the new version installed? The warnings have disappeared on my instance after this test version.

**Comment by Brandawg93** [comment]
Ok. I've published a new test (v1.3.1-test.1) that should hopefully fix those battery errors. Let me know if that works for you.

**Comment by captconstruct** [comment]
That looks like it fixed the error for me. Thanks!

From: Brandon McFarlin ***@***.***>
Reply-To: Brandawg93/homebridge-fordpass ***@***.***>
Date: Saturday, March 13, 2021 at 3:57 PM
To: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Blake Singleton ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-fordpass] Errors generated when loading plugin (#134)


Ok. I've published a new test (v1.3.1-test.1) that should hopefully fix those battery errors. Let me know if that works for you.

**Comment by Brandawg93** [comment]
Thanks for the help testing this! I've published v1.3.1 which should include these fixes.

**Comment by captconstruct** [comment]
No problem! Thanks for making this awesome plugin.

From: Brandon McFarlin ***@***.***>
Reply-To: Brandawg93/homebridge-fordpass ***@***.***>
Date: Monday, March 15, 2021 at 9:57 AM
To: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Blake Singleton ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-fordpass] Errors generated when loading plugin (#134)


Thanks for the help testing this! I've published v1.3.1 which should include these fixes.

**Comment by captconstruct** [comment]
Update: I’m now getting new errors and I’m getting a lot of notifications of my cars locking and unlocking.

Errors are:

[3/15/2021, 11:32:36 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:32:36 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:32:55 AM] [FordPass] Status failed with error: ECONNRESET
[3/15/2021, 11:33:36 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:34:09 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:34:09 AM] [FordPass] Cannot get information for F150 engine
[3/15/2021, 11:34:14 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:34:14 AM] [FordPass] Cannot get information for Edge engine
[3/15/2021, 11:34:36 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:34:37 AM] [FordPass] Status failed with error: ETIMEDOUT
[3/15/2021, 11:34:37 AM] [FordPass] Cannot get information for Edge lock
[3/15/2021, 11:35:54 AM] [FordPass] Status failed with error: ECONNRESET
[3/15/2021, 11:36:22 AM] [FordPass] Status failed with error: ECONNRESET
[3/15/2021, 11:36:22 AM] [FordPass] Cannot get information for Edge engine
[3/15/2021, 11:36:36 AM] [FordPass] Status failed with error: EAI_AGAIN
[3/15/2021, 11:36:58 AM] [FordPass] Status failed with error: ETIMEDOUT
[3/15/2021, 11:37:30 AM] [FordPass] Status failed with error: ECONNRESET
[3/15/2021, 11:37:35 AM] [FordPass] Status failed with error: ECONNRESET

This coincides with notifications at rapid fire pacing of F150 locked/unlocked and Edge locked/unlocked about 10 or so times in a few seconds. This has only happened once, but it didn’t occur until I updated to the latest test build.

From: Brandon McFarlin ***@***.***>
Reply-To: Brandawg93/homebridge-fordpass ***@***.***>
Date: Monday, March 15, 2021 at 9:57 AM
To: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Blake Singleton ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-fordpass] Errors generated when loading plugin (#134)


Thanks for the help testing this! I've published v1.3.1 which should include these fixes.

**Comment by Brandawg93** [comment]
You can turn the notifications off in the Home app if you don't want them on.

I think Ford's API is currently down since mine is doing this as well. I would wait a while and try again.

**Comment by captconstruct** [comment]
Will do. Thanks again.


From: Brandon McFarlin ***@***.***>
Reply-To: Brandawg93/homebridge-fordpass ***@***.***>
Date: Monday, March 15, 2021 at 11:43 AM
To: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Blake Singleton ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-fordpass] Errors generated when loading plugin (#134)


You can turn the notifications off in the Home app if you don't want them on.

I think Ford's API is currently down since mine is doing this as well. I would wait a while and try again.
